### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by gerep** [slim-template/vim-slim#58]
Is this project abandoned?

**Comment by xiaozi0lei** [comment]
this plugin not works now. :sad:

**Comment by burningTyger** [comment]
@xiaozi0lei why not? Works for me.

**Comment by pachonk** [comment]
@gerep @xiaozi0lei What's broke?

**Comment by evmorov** [comment]
@pachonk, https://github.com/slim-template/vim-slim/issues/19?

**Comment by pachonk** [comment]
Sounds good. Looks like https://github.com/onemanstartup/vim-slim has some fixes that should help too.
